# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential vim gdb git docker.io docker-compose
	  usermod -a -G docker ubuntu
  SHELL
end
